name: Create EKS cluster
on: [workflow_dispatch]
env:
  REGION: us-east-1
  CLUSTER: quarkus-kubernetes
jobs:
  create_cluster:
    runs-on: ubuntu-latest
    name: Create an EKS on Fargate cluster
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Provision cluster
        uses: aws-actions/amazon-eks-fargate@v0.1