name: Create EKS cluster
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Set the environment to execute'
        required: true
        default: prod
      region:
        description: 'set the AWS region to create the cluster'
        required: true
        default: us-west-2
      kubernetes_version:
        description: 'set the kubernetes cluster version'
        required: true
        default: "1.20"

env:
  REGION: ${{ github.event.inputs.region }}
  CLUSTER: ${{ github.event.repository.name }}-${{ github.event.inputs.environment }}
  VERSION: ${{ github.event.inputs.kubernetes_version }}
jobs:
  create_cluster:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    name: Create an EKS on Fargate cluster
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      - name: Provision cluster
        uses: DanielFidalgo/amazon-eks-fargate@master
      - name: Recover kube config in base64
        id: kube-config
        run: |
        echo "::set-output name=base64-encripted::$(cat ~/.kube/config | base64)"
      - name: update SECRET
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'KUBE_CONFIG_DATA'
          value: ${{ steps.kube-config.outputs.base64-encripted }}
          repository: hmanzur/actions-set-secret
          token: ${{ github.token }}

